### ISSUE TITLE
Kurzzeitige Verlangsamung

### ISSUE THREAD

**Issue by 96Sabiii** [Kotjik/Flappy-Bird-2#22]
Als Nutzer möchte ich durch Spielmechaniken wie kurzzeitige Verlangsamung des Spiels einen vorübergehenden Vorteil für das Spiel, um so das Spielerlebnis zu verbessern.

**Comment by AboutWhite** [comment]
Es gibt im Gamemanager die Funktion ChangeGameSpeed der einfach ein Wert übergeben wird. Das müsste dann der/ diejenige machen der die items macht oder?

**Comment by Kotjik** [comment]
Implementiert in Bird.cs 
Jedoch anders: Die Figur wird "schwerer"  und kann sich langsamer nach oben bzw. zur Seite bewegen.
--> Nach drei Sekunden Rücksetzung auf Normal-Werte

Fehlt: Visueller Hinweis, dass der Vogel langsamer wurde (z.B. Eisenkugel am Bein)
