### ISSUE TITLE
Kurzzeitige Verschnellerung

### ISSUE THREAD

**Issue by 96Sabiii** [Kotjik/Flappy-Bird-2#26]
Als Nutzer möchte ich durch Spielmechaniken wie kurzzeitige Verschnellerung einen vorübergehenden Nachteil für das Spiel, um das Spiel schwieriger zu gestalten und so das Spielerlebnis zu verbessern.

**Comment by AboutWhite** [comment]
Genau das gleiche wie bei der Verlangsamung. Im GameManager ChangeSpeed nutzten. Wenn ich da noch was machen soll müssten wir das nochmal besprechen

**Comment by Kotjik** [comment]
Implementiert in Bird.cs 
Jedoch anders: Die Figur wird "leichter" und kann sich schneller nach oben bzw. zur Seite bewegen.
--> Nach drei Sekunden Rücksetzung auf Normal-Werte

Fehlt: Visueller Hinweis, dass der Vogel langsamer wurde (z.B. Feder am Kopf)
