### ISSUE TITLE
Lähmung

### ISSUE THREAD

**Issue by 96Sabiii** [Kotjik/Flappy-Bird-2#27]
Als Nutzer möchte ich durch Spielmechaniken wie kurzzeitige Lähmung der Spielfigur (verzögerte / geringere Reaktion nach oben) einen vorübergehenden Nachteil für das Spiel, um das Spiel schwieriger zu gestalten und so das Spielerlebnis zu verbessern.

**Comment by Kotjik** [comment]
Das gleiche wie #22 .
