### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by 96Sabiii** [Kotjik/Flappy-Bird-2#28]
Als Nutzer möchte ich für einen passenden Ton für bestimmte Spielmechaniken um auch auditiv vom Spiel abgeholt zu werden.
- Flügelschlag/Springgeräusch
- Hindernis geschafft
- Hindernis nicht geschafft / 1 Leben verloren
- Neuer Highscore
- Alle Leben verloren / Tod
- allgemeine Hintergrundmusik

**Comment by 96Sabiii** [comment]
z.B. New Highscore / Achievement:
https://freesound.org/people/LittleRobotSoundFactory/sounds/270330/
https://freesound.org/people/LittleRobotSoundFactory/sounds/274177/
https://freesound.org/people/plasterbrain/sounds/242855/

Hindernis nicht geschafft:
https://freesound.org/people/GameAudio/sounds/220203/
https://freesound.org/people/danlucaz/sounds/517753/
https://freesound.org/people/cabled_mess/sounds/371451/
https://freesound.org/people/themusicalnomad/sounds/253886/

**Comment by veraarev** [comment]
Hintergrundmusik Spiel
Hintergrundmusik Menü

Weitere Sounds sind vorhanden:
- Button Click
- Bird scored
- Bird crashed
- Items
