### ISSUE TITLE
Vogel bewegt sich nach links, wenn er gegen ein Gegenstand fliegt. 

### ISSUE THREAD

**Issue by buraks95** [Kotjik/Flappy-Bird-2#37]
Wenn der Vogel gegen einen Gegenstand trifft und Leben verliert, kann er nicht weiterfliegen, sodass er sich immer weiter nach links bewegt. Theoretisch sogar aus dem Fenster raus.

**Comment by Kotjik** [comment]
Gelöst: Man kann den Vogel mittels Pfeil nach links und rechts oder "A" und "D" bewegen. Außerdem kann der Vogel nicht mehr aus dem Bild verschwinden.
