### ISSUE TITLE
Bei Hinderniss vor und wieder zurück fliegen, kreigt man jedes mal Punkte

### ISSUE THREAD

**Issue by Kotjik** [Kotjik/Flappy-Bird-2#52]

**Comment by 96Sabiii** [comment]
Trigger wird aktuell für 7 Sekunden pausiert, sodass man nicht erneut Punkten kann.
Bis zu einem Score von 37 führt das zu keinen Fehlern (Das Punkten nicht möglich ist, da der Trigger noch immer deaktiviert ist)
